name: Strapi ECS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    #####################################
    # Terraform
    #####################################

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan

    #####################################
    # ECR Login + Docker
    #####################################

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Image
      run: docker build -t strapi-app ./strapi-app

    - name: Tag Image
      run: |
        docker tag strapi-app:latest 811738710312.dkr.ecr.us-east-1.amazonaws.com/noor-strapi:latest

    - name: Push Image
      run: |
        docker push 811738710312.dkr.ecr.us-east-1.amazonaws.com/noor-strapi:latest

    #####################################
    # Deployment (Do NOT Put Terraform Apply Here)
    #####################################
