name: Strapi ECS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    #####################################
    # Checkout Code
    #####################################

    - name: Checkout Repository
      uses: actions/checkout@v3

    #####################################
    # Configure AWS Credentials
    #####################################

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    #####################################
    # Login to ECR
    #####################################

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    #####################################
    # Build + Push Docker Image
    #####################################

    - name: Build Docker Image
      run: |
        docker build -t strapi-app ./strapi-app

    - name: Tag Image
      run: |
        docker tag strapi-app:latest ${{ steps.login-ecr.outputs.registry }}/strapi:latest

    - name: Push Image to ECR
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/strapi:latest

    #####################################
    # Terraform Setup
    #####################################

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan

    #####################################
    # Apply Infrastructure Changes
    #####################################

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve
